### ISSUE TITLE
Adjust title and description

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-pages#18]
Currently it is not immediately clear that skohub-docker-vocabs provides a way to publish your vocabs with GitHub pages. This should be made clearer at least from the description, maybe also by adjusting the repp/module name.

**Comment by sroertgen** [comment]
Name and Description is already adapter: https://github.com/skohub-io/skohub-pages?tab=readme-ov-file#skohub-vocabs-serverless

Does this already meet the requirements?

**Comment by acka47** [comment]
+1 Closing.
