### ISSUE TITLE
Use the GitHub Pages domain in your vocabulary and make it resolve to your vocabulary

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-pages#21]
It should be possible to actually have working and resolving links when publishing a vocabulary via the GitHub Pages approach

Related https://github.com/skohub-io/skohub-vocabs/issues/26

**Comment by sroertgen** [comment]
@acka47 you can test this now.

The setup is described in the README 8https://github.com/skohub-io/skohub-docker-vocabs?tab=readme-ov-file#custom-domain)

**Comment by acka47** [comment]
This works great, see https://acka47.github.io/skohub-pages/

Some example URIs:

- vocab: https://acka47.github.io/skohub-pages/colour-with-hierarchy/
- Concept: https://acka47.github.io/skohub-pages/hcrt/lesson_plan
- Collection: https://acka47.github.io/skohub-pages/hcrt/test_collection

**Comment by sroertgen** [comment]
Maybe we should just add a constraint/hint for SkoHub Vocabs that `.../index` is not a recommended URI

**Comment by acka47** [comment]
Done with https://github.com/skohub-io/skohub-pages/pull/22, announced in https://blog.skohub.io/2024-03-21-skohub-pages/. Closing.
