### ISSUE TITLE
Create/link an example repo based on this workflow/repo

### ISSUE THREAD

**Issue by dalito** [skohub-io/skohub-pages#25]
For people who like to quickly see the result of  https://blog.skohub.io/2024-03-21-skohub-pages/ you could create a simple example vocabulary repo including vocabulary documentation generated from it.

BTW, we have developed a github (+xlsx) based curation workflow in NFDI4Cat around [voc4cat](https://github.com/search?q=org%3Anfdi4cat+voc4cat&type=repositories) which you may find interesting.

**Comment by acka47** [comment]
Thanks for the hint. We will add this to the blog post.

**Comment by acka47** [comment]
The skohub-pages repo already contains some example vocabs. I assume it would suffice then to link to https://skohub-io.github.io/skohub-pages/ in the blog so that people can take a look at the SkoHub build, wouldn't it?

**Comment by dalito** [comment]
Yes. I this will make clear what the result will look like. 

I need to look into your doc generation in more detail when I have more time. We use a customized version of pylode2 at the moment. It is OKish but not perfect.

**Comment by acka47** [comment]
I have opened a PR at https://github.com/skohub-io/skohub-blog/pull/39 with an added sentence including the link. Is it ok like this or would you imagine for it to be more prominent, @dalito ?

**Comment by dalito** [comment]
Looks good to me. Thank you!

**Comment by acka47** [comment]
Great, thanks again. PR is merged and new version is online at https://blog.skohub.io/2024-03-21-skohub-pages/ (unfortunately with a double "example" in the sentence but I will just leave it like that).
