### ISSUE TITLE
Github actions workflow fails due to deprecated Node.js 16 actions.

### ISSUE THREAD

**Issue by LasseMempel** [skohub-io/skohub-pages#27]
I followed the recommended procedure to test a skohub-page and it failed to complete the Github action.
This seems to be due to deprecated Node.js 16 actions (see attached image).

![Screenshot 2024-06-10 134650](https://github.com/skohub-io/skohub-pages/assets/76393066/1a1f3f9b-78b2-48f5-bde6-18399324359e)

**Comment by LasseMempel** [comment]
Dear @acka47,
thank you so much for your help and effort!
As this was my first time to fork another project and use github-action workflows I didn't find the errors of the run and misinterpreted the warnings about Node.js versions.
After your help i found them. Nontheless it might still be a good idea to  give a hint about the required Scheme of the ttl file.

**Comment by acka47** [comment]
You are welcome and thanks again for the report. I have opened #28 to add a hint regarding the SHACL validation to the troubleshooting section in the README.
